build:
    environment:
        php:
            version: '7.2'
    tests:
        override:
            -
                command: './bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: './var/reports/clover.xml'
                    format: 'php-clover'

checks:
    php: true

coding_style:
    php: {}

filter:
    excluded_paths:
        - 'tests/*'