build:
    environment:
        php:
            version: '7.2'
    tests:
        override:
            -
                command: './vendor/bin/phpunit'
                coverage:
                    file: './build/logs/clover.xml'
                    format: 'php-clover'

checks:
    php: true

coding_style:
    php: {}

filter:
    excluded_paths:
        - 'tests/*'