language: php
sudo: false

notifications:
    email: false

cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/symfony-bridge/.phpunit

matrix:
    fast_finish: true
      include:
        - php: 7.1
        - php: 7.2
        - php: nightly
      allow_failures:
        - php: nightly

before_install:
    - phpenv config-rm xdebug.ini
    - yes '' | pecl install -f apcu-5.1.8
    - composer self-update

install:
  - composer install --prefer-dist --no-suggest --classmap-authoritative --no-interaction
  - bin/simple-phpunit install

script:
    - composer lint
    - composer cs
    - ./bin/phpunit --no-coverage