language: php
sudo: false

notifications:
    email: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 7.2
          env:
              - SYMFONY_VERSION=4.0.*
        - php: 7.2
        - php: hhvm
        - php: nightly
    allow_failures:
        - php: hhvm
        - php: nightly

before_install:
    - composer self-update
    - if [[ ! $SYMFONY_VERSION ]]; then composer update; fi;
    - if [[ $SYMFONY_VERSION ]]; then composer require symfony/symfony:${SYMFONY_VERSION} -n; fi;

script:
    - ./bin/phpunit --no-coverage